#!/usr/bin/env bash
# categorize_audio_by_git_date.sh (date format YYYYMMDD)
# Git-Bash (Windows 11) compatible.
# Renames ALL tracked .wav/.mp3 files in the repo recursively by prefixing with
# the date they were first added to git: YYYYMMDD__originalname.ext
#
# Dry-run is default. Use --apply to rename via `git mv`.
# Verbose logging is ON by default. Use --quiet to reduce logs.

set -u
set -o pipefail

MODE="dry-run"
VERBOSE=1

usage() {
  echo "Usage: $0 [--dry-run|--apply] [--quiet]"
  exit 2
}

for arg in "$@"; do
  case "$arg" in
    --apply) MODE="apply" ;;
    --dry-run) MODE="dry-run" ;;
    --quiet) VERBOSE=0 ;;
    *) usage ;;
  esac
done

MAP_CSV="audio_rename_map.csv"
UNDO_SH="undo_renames.sh"

log() {
  if [[ "${VERBOSE:-1}" -eq 1 ]]; then
    echo "[LOG] $*"
  fi
}

warn() { echo "[WARN] $*" >&2; }
err()  { echo "[ERR]  $*" >&2; }

# Ensure git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  err "Not inside a git repository."
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT" || { err "Failed to cd to repo root: $REPO_ROOT"; exit 1; }

log "Mode: $MODE"
log "Repo root: $REPO_ROOT"
log "Scanning entire repo recursively for .wav/.mp3 ..."

# Initialize outputs
echo "old_path,new_path,date,commit_sha,status" > "$MAP_CSV"
cat > "$UNDO_SH" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Undo script generated by categorize_audio_by_git_date.sh
# Run from repo root.
EOF
chmod +x "$UNDO_SH" 2>/dev/null || true
log "Wrote headers: $MAP_CSV, $UNDO_SH"

declare -A planned_targets=()
declare -A date_counts=()

total_scanned=0
skipped_prefixed=0
no_add_commit=0
planned_renames=0
apply_ok=0
apply_err=0
non_audio_seen=0

declare -a examples=()

is_audio_file() {
  shopt -s nocasematch
  [[ "$1" == *.wav || "$1" == *.mp3 ]]
  local rc=$?
  shopt -u nocasematch
  return $rc
}

# Updated: match YYYYMMDD__ (8 digits, no dashes)
already_prefixed() {
  [[ "$1" =~ ^[0-9]{8}__ ]]
}

# make_target unchanged except receives date in YYYYMMDD format
make_target() {
  local dir="$1"
  local base="$2"
  local ext="$3"
  local date="$4"       # now YYYYMMDD
  local shortsha="$5"

  local stem="$base"
  [[ -n "$ext" ]] && stem="${base%$ext}"

  local candidate="${dir}/${date}__${base}"
  candidate="${candidate#./}"

  if [[ -e "$candidate" || -n "${planned_targets["$candidate"]+x}" ]]; then
    log "Collision detected for target: $candidate"
    candidate="${dir}/${date}__${stem}__${shortsha}${ext}"
    candidate="${candidate#./}"
  fi

  if [[ -e "$candidate" || -n "${planned_targets["$candidate"]+x}" ]]; then
    log "Collision persists; adding numeric suffix for: $candidate"
    local n=2
    while :; do
      local alt="${dir}/${date}__${stem}__${shortsha}__${n}${ext}"
      alt="${alt#./}"
      if [[ ! -e "$alt" && -z "${planned_targets["$alt"]+x}" ]]; then
        candidate="$alt"
        break
      fi
      n=$((n+1))
    done
  fi

  echo "$candidate"
}

# helper to convert YYYY-MM-DD -> YYYYMMDD
compact_date() {
  local dashed="$1"
  # Expect input like 2025-01-30; produce 20250130
  echo "${dashed//-/}"
}

# MAIN LOOP
while IFS= read -r -d '' f; do
  f="${f#./}"

  if ! is_audio_file "$f"; then
    non_audio_seen=$((non_audio_seen+1))
    continue
  fi

  total_scanned=$((total_scanned+1))

  base="$(basename "$f")"
  dir="$(dirname "$f")"

  log "----"
  log "[$total_scanned] Audio file: $f"
  log "dir=$dir base=$base"

  if already_prefixed "$base"; then
    skipped_prefixed=$((skipped_prefixed+1))
    log "SKIP already prefixed: $base"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$f\"" "" "" "SKIP_ALREADY_PREFIXED" >> "$MAP_CSV"
    continue
  fi

  log "Running: git log --diff-filter=A --follow --format=%H -- \"$f\""
  sha="$(git log --diff-filter=A --follow --format=%H -- "$f" 2>/dev/null | tail -n 1 || true)"

  if [[ -z "$sha" ]]; then
    no_add_commit=$((no_add_commit+1))
    warn "NO_ADD_COMMIT for: $f"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$f\"" "" "" "NO_ADD_COMMIT" >> "$MAP_CSV"
    continue
  fi

  log "Add-commit SHA: $sha"
  log "Running: git show -s --format=%ad --date=short \"$sha\""
  date_added_dashed="$(git show -s --format=%ad --date=short "$sha" 2>/dev/null || true)"

  if [[ -z "$date_added_dashed" ]]; then
    apply_err=$((apply_err+1))
    err "ERROR_NO_DATE for sha=$sha file=$f"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$f\"" "" "\"$sha\"" "ERROR_NO_DATE" >> "$MAP_CSV"
    continue
  fi

  # Convert to compact YYYYMMDD
  date_added="$(compact_date "$date_added_dashed")"
  shortsha="${sha:0:7}"
  log "Date added: $date_added_dashed -> compact: $date_added (shortsha=$shortsha)"

  ext=""
  [[ "$base" == *.* ]] && ext=".${base##*.}"
  log "Extension: '${ext:-<none>}'"

  target="$(make_target "$dir" "$base" "$ext" "$date_added" "$shortsha")"
  log "Proposed target: $target"

  planned_targets["$target"]=1
  planned_renames=$((planned_renames+1))
  date_counts["$date_added"]=$(( ${date_counts["$date_added"]:-0} + 1 ))

  if (( ${#examples[@]} < 30 )); then
    examples+=("$f -> $target")
  fi

  if [[ "$MODE" == "dry-run" ]]; then
    log "DRY-RUN: would rename using: git mv -- \"$f\" \"$target\""
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$target\"" "\"$date_added\"" "\"$sha\"" "PLANNED" >> "$MAP_CSV"
    echo "git mv -- \"$target\" \"$f\"" >> "$UNDO_SH"
  else
    log "APPLY: executing: git mv -- \"$f\" \"$target\""
    if git mv -- "$f" "$target"; then
      apply_ok=$((apply_ok+1))
      log "RENAMED_OK: $f -> $target"
      printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$target\"" "\"$date_added\"" "\"$sha\"" "RENAMED_OK" >> "$MAP_CSV"
      echo "git mv -- \"$target\" \"$f\"" >> "$UNDO_SH"
    else
      apply_err=$((apply_err+1))
      err "RENAMED_ERROR: $f -> $target"
      printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$target\"" "\"$date_added\"" "\"$sha\"" "RENAMED_ERROR" >> "$MAP_CSV"
      echo "# FAILED: git mv -- \"$target\" \"$f\"" >> "$UNDO_SH"
      echo "echo \"FAILED undo for: $target -> $f\"" >> "$UNDO_SH"
    fi
  fi

done < <(find . -type f -print0)

log "----"
log "Finished scanning."

echo ""
echo "Summary:"
echo "  Total audio files processed:  $total_scanned"
echo "  Skipped (already prefixed):   $skipped_prefixed"
echo "  No add-commit found:          $no_add_commit"
echo "  Planned renames:              $planned_renames"
if [[ "$MODE" == "apply" ]]; then
  echo "  Applied OK:                   $apply_ok"
  echo "  Applied errors:               $apply_err"
fi
echo "  Non-audio files encountered:  $non_audio_seen"

echo ""
echo "Top 20 dates by file count (YYYYMMDD):"
if (( ${#date_counts[@]} > 0 )); then
  for d in "${!date_counts[@]}"; do
    echo "${date_counts[$d]} $d"
  done | sort -nr | head -20 | awk '{printf "  %s (%s files)\n",$2,$1}'
else
  echo "  (none)"
fi

echo ""
echo "First 30 examples:"
if (( ${#examples[@]} == 0 )); then
  echo "  (none)"
else
  for ex in "${examples[@]}"; do
    echo "  $ex"
  done
fi

echo ""
echo "Wrote:"
echo "  $MAP_CSV"
echo "  $UNDO_SH"

if [[ "$MODE" == "dry-run" ]]; then
  echo ""
  echo "Next:"
  echo "  Run with --apply to execute renames:"
  echo "    ./$0 --apply"
  echo "  Or reduce logs:"
  echo "    ./$0 --dry-run --quiet"
fi
