#!/usr/bin/env bash
# categorize_audio_by_git_date_copy.sh (verbose, YYYYMMDD, COPY into timestamped/, Ctrl+C friendly, precheck target before git, process smallest files first)
# Git-Bash (Windows 11) compatible.
#
# Copies tracked .wav/.mp3 files (anywhere in repo) to a mirrored path under `timestamped/`,
# prefixing the basename with the date it was first added to git:
#
#   <orig/path/file.ext>
#     -> timestamped/<orig/path/YYYYMMDD__file.ext>
#
# Example:
#   algorhythms/01242025_1.plucks 120bpm.wav
#     -> timestamped/algorhythms/20250130__01242025_1.plucks 120bpm.wav
#
# Key behaviors:
# - Original files remain untouched.
# - Date prefix is YYYYMMDD (no dashes).
# - Skips source files whose basename already starts with YYYYMMDD__ (avoids double-prefixing).
# - Skips files inside timestamped/ (prevents recursion/dup).
# - Precheck BEFORE ANY git calls: if any prior timestamped copy exists for this source in the dest folder, skip.
# - Collision policy after date is known:
#     1) If primary dest exists/planned, try __<shortsha>
#     2) If hash dest exists/planned, SKIP (no __2/__3)
# - Trims characters from END of stem to keep basename bounded (Windows-friendly).
# - Processes files in ascending size order (smallest first).
# - Ctrl+C (SIGINT) exits quickly with exit code 130.
#
# Dry-run is default. Use --apply to actually copy.
# Verbose logging is ON by default. Use --quiet to reduce logs.

set -u
set -o pipefail

MODE="dry-run"
VERBOSE=1

DEST_ROOT="timestamped"
MAX_BASENAME_LEN=120

MAP_CSV="audio_copy_map.csv"
UNDO_SH="undo_copies.sh"

# Interrupt handling (Ctrl+C)
INTERRUPTED=0
trap '
  INTERRUPTED=1
  echo ""
  echo "[INTERRUPT] Ctrl+C received. Exiting safely..."
  echo "[INTERRUPT] Partial outputs (so far):"
  echo "  - ${MAP_CSV:-audio_copy_map.csv}"
  echo "  - ${UNDO_SH:-undo_copies.sh}"
  exit 130
' INT

usage() {
  echo "Usage: $0 [--dry-run|--apply] [--quiet]"
  exit 2
}

for arg in "$@"; do
  case "$arg" in
    --apply) MODE="apply" ;;
    --dry-run) MODE="dry-run" ;;
    --quiet) VERBOSE=0 ;;
    *) usage ;;
  esac
done

log() {
  if [[ "${VERBOSE:-1}" -eq 1 ]]; then
    echo "[LOG] $*"
  fi
}
warn() { echo "[WARN] $*" >&2; }
err()  { echo "[ERR]  $*" >&2; }

# Ensure git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  err "Not inside a git repository."
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT" || { err "Failed to cd to repo root: $REPO_ROOT"; exit 1; }

log "Mode: $MODE"
log "Repo root: $REPO_ROOT"
log "Destination root: $DEST_ROOT/"
log "Scanning entire repo recursively for .wav/.mp3 (smallest first) ..."

# Initialize outputs
echo "old_path,new_path,date,commit_sha,status" > "$MAP_CSV"
cat > "$UNDO_SH" <<EOF
#!/usr/bin/env bash
set -euo pipefail
# Undo script generated by $(basename "$0")
# Run from repo root.
# Deletes copied files under: $DEST_ROOT/
EOF
chmod +x "$UNDO_SH" 2>/dev/null || true
log "Wrote headers: $MAP_CSV, $UNDO_SH"

declare -A planned_targets=()
declare -A date_counts=()

total_scanned=0
skipped_prefixed=0
skipped_in_dest_root=0
skipped_precheck_exists=0
skipped_already_exists=0
no_add_commit=0
planned_copies=0
apply_ok=0
apply_err=0
non_audio_seen=0

declare -a examples=()

is_audio_file() {
  shopt -s nocasematch
  [[ "$1" == *.wav || "$1" == *.mp3 ]]
  local rc=$?
  shopt -u nocasematch
  return $rc
}

already_prefixed() {
  [[ "$1" =~ ^[0-9]{8}__ ]]
}

compact_date() {
  echo "${1//-/}"
}

trim_stem() {
  local stem="$1"
  local maxlen="$2"
  if (( ${#stem} > maxlen )); then
    echo "${stem:0:maxlen}"
  else
    echo "$stem"
  fi
}

# Precheck for any prior timestamped copy without git history lookups.
# Looks for:
#   timestamped/<dir>/????????__<trimmedStem><ext>
#   timestamped/<dir>/????????__<trimmedStem>__???????<ext>
precheck_any_existing_copy() {
  local src_rel="$1"
  local src_dir src_base
  src_dir="$(dirname "$src_rel")"
  src_base="$(basename "$src_rel")"

  local dest_dir="${DEST_ROOT}/${src_dir}"
  dest_dir="${dest_dir#./}"

  [[ -d "$dest_dir" ]] || return 1

  local ext=""
  if [[ "$src_base" == *.* ]]; then
    ext=".${src_base##*.}"
  fi
  local stem="$src_base"
  [[ -n "$ext" ]] && stem="${src_base%$ext}"

  # Apply the same trimming policy
  local prefix_len=8
  prefix_len=$((prefix_len + 2))     # "__"
  local reserved_collision=9         # "__" + 7
  local allowed_stem_len=$((MAX_BASENAME_LEN - prefix_len - reserved_collision))
  (( allowed_stem_len < 10 )) && allowed_stem_len=10
  stem="$(trim_stem "$stem" "$allowed_stem_len")"

  local p1="${dest_dir}/????????__${stem}${ext}"
  local p2="${dest_dir}/????????__${stem}__???????${ext}"

  compgen -G "$p1" >/dev/null && return 0
  compgen -G "$p2" >/dev/null && return 0
  return 1
}

# After date is known, compute a concrete destination.
# Collision policy:
#   - if primary exists/planned, try __shortsha
#   - if hash exists/planned, SKIP
make_dest_path() {
  local src_rel="$1"
  local date="$2"
  local shortsha="$3"

  local src_dir src_base
  src_dir="$(dirname "$src_rel")"
  src_base="$(basename "$src_rel")"

  local ext=""
  if [[ "$src_base" == *.* ]]; then
    ext=".${src_base##*.}"
  fi
  local stem="$src_base"
  [[ -n "$ext" ]] && stem="${src_base%$ext}"

  local prefix_len=${#date}
  prefix_len=$((prefix_len + 2))
  local reserved_collision=9
  local allowed_stem_len=$((MAX_BASENAME_LEN - prefix_len - reserved_collision))
  (( allowed_stem_len < 10 )) && allowed_stem_len=10

  local original_stem_len=${#stem}
  stem="$(trim_stem "$stem" "$allowed_stem_len")"
  if (( original_stem_len != ${#stem} )); then
    log "Trimmed stem: ${original_stem_len} -> ${#stem} chars to enforce MAX_BASENAME_LEN=$MAX_BASENAME_LEN"
  fi

  local dest_dir="${DEST_ROOT}/${src_dir}"
  dest_dir="${dest_dir#./}"

  local candidate="${dest_dir}/${date}__${stem}${ext}"

  if [[ -e "$candidate" || -n "${planned_targets["$candidate"]+x}" ]]; then
    log "Collision detected for dest: $candidate"
    candidate="${dest_dir}/${date}__${stem}__${shortsha}${ext}"

    if [[ -e "$candidate" || -n "${planned_targets["$candidate"]+x}" ]]; then
      echo "__SKIP_ALREADY_EXISTS__:$candidate"
      return
    fi
  fi

  echo "$candidate"
}

# Ensure destination root exists (apply mode)
if [[ "$MODE" == "apply" ]]; then
  mkdir -p "$DEST_ROOT" || { err "Failed to create $DEST_ROOT/"; exit 1; }
fi

# --- Build a sorted (by size) list of candidate files, then process it ---
# We generate NUL-delimited list with find, then use git-bash's `stat -c%s` to get size.
# Output format: "<size>\t<path>\0" then sort numeric and iterate.
log "Building size-sorted file list (this may take a moment)..."

sorted_list_file="$(mktemp -t audio_sorted_list.XXXXXX)"
cleanup() { rm -f "$sorted_list_file" 2>/dev/null || true; }
trap 'cleanup; exit 130' INT

# Create list
# Note: stat -c%s is available in Git Bash coreutils.
while IFS= read -r -d '' p; do
  p="${p#./}"

  # Skip anything inside DEST_ROOT early to reduce work
  if [[ "$p" == "$DEST_ROOT/"* ]]; then
    continue
  fi

  if ! is_audio_file "$p"; then
    continue
  fi

  # If stat fails, treat size as large
  sz="$(stat -c%s -- "$p" 2>/dev/null || echo 999999999999)"
  printf '%s\t%s\0' "$sz" "$p" >> "$sorted_list_file"
done < <(find . -type f -print0)

# Sort by size (numeric) while preserving NUL delimiters by translating to newlines for sort,
# then back to NUL. Safe enough because file paths from Git Bash typically don't contain newlines.
sorted_stream="$(mktemp -t audio_sorted_stream.XXXXXX)"
# shellcheck disable=SC2064
trap "cleanup; rm -f '$sorted_stream' 2>/dev/null || true; exit 130" INT

python - <<'PY' "$sorted_list_file" "$sorted_stream"
import sys
src, dst = sys.argv[1], sys.argv[2]
data = open(src, "rb").read().split(b"\0")
rows = [r for r in data if r]
rows.sort(key=lambda r: int(r.split(b"\t",1)[0]))
with open(dst, "wb") as f:
    for r in rows:
        f.write(r + b"\0")
PY

rm -f "$sorted_list_file" 2>/dev/null || true
sorted_list_file="$sorted_stream"

log "Processing sorted files..."

# MAIN LOOP over sorted list
while IFS= read -r -d '' rec; do
  if (( INTERRUPTED )); then
    err "Interrupted flag set; exiting loop."
    cleanup
    exit 130
  fi

  # record format: "<size>\t<path>"
  size="${rec%%$'\t'*}"
  f="${rec#*$'\t'}"

  # Safety: ignore empties
  [[ -n "$f" ]] || continue

  # Maintain some counters for visibility
  base="$(basename "$f")"

  log "----"
  log "Audio file: $f (size=${size} bytes)"

  if already_prefixed "$base"; then
    skipped_prefixed=$((skipped_prefixed+1))
    log "SKIP already prefixed: $base"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$f\"" "" "" "SKIP_ALREADY_PREFIXED" >> "$MAP_CSV"
    continue
  fi

  # Precheck BEFORE ANY git calls
  log "Precheck: looking for existing timestamped copy without git history..."
  if precheck_any_existing_copy "$f"; then
    skipped_precheck_exists=$((skipped_precheck_exists+1))
    log "SKIP precheck: found an existing copy under $DEST_ROOT/ for $f"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"\"" "" "" "SKIP_PRECHECK_EXISTS" >> "$MAP_CSV"
    continue
  fi

  total_scanned=$((total_scanned+1))

  log "Running: git log --diff-filter=A --follow --format=%H -- \"$f\""
  sha="$(git log --diff-filter=A --follow --format=%H -- "$f" 2>/dev/null | tail -n 1 || true)"
  if [[ -z "$sha" ]]; then
    no_add_commit=$((no_add_commit+1))
    warn "NO_ADD_COMMIT for: $f"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$f\"" "" "" "NO_ADD_COMMIT" >> "$MAP_CSV"
    continue
  fi

  log "Add-commit SHA: $sha"
  log "Running: git show -s --format=%ad --date=short \"$sha\""
  date_added_dashed="$(git show -s --format=%ad --date=short "$sha" 2>/dev/null || true)"
  if [[ -z "$date_added_dashed" ]]; then
    apply_err=$((apply_err+1))
    err "ERROR_NO_DATE for sha=$sha file=$f"
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$f\"" "" "\"$sha\"" "ERROR_NO_DATE" >> "$MAP_CSV"
    continue
  fi

  date_added="$(compact_date "$date_added_dashed")"
  shortsha="${sha:0:7}"
  log "Date added: $date_added_dashed -> compact: $date_added (shortsha=$shortsha)"

  dest_path="$(make_dest_path "$f" "$date_added" "$shortsha")"
  if [[ "$dest_path" == __SKIP_ALREADY_EXISTS__:* ]]; then
    skipped_already_exists=$((skipped_already_exists+1))
    actual_path="${dest_path#__SKIP_ALREADY_EXISTS__:}"
    log "SKIP already exists (base + hash): $actual_path"
    printf '%s,%s,%s,%s,%s\n' \
      "\"$f\"" "\"$actual_path\"" "\"$date_added\"" "\"$sha\"" "SKIP_ALREADY_EXISTS" >> "$MAP_CSV"
    continue
  fi

  log "Destination: $dest_path"

  planned_targets["$dest_path"]=1
  planned_copies=$((planned_copies+1))
  date_counts["$date_added"]=$(( ${date_counts["$date_added"]:-0} + 1 ))

  if (( ${#examples[@]} < 30 )); then
    examples+=("$f -> $dest_path")
  fi

  if [[ "$MODE" == "dry-run" ]]; then
    log "DRY-RUN: would copy: cp -p -- \"$f\" \"$dest_path\""
    printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$dest_path\"" "\"$date_added\"" "\"$sha\"" "PLANNED" >> "$MAP_CSV"
    echo "rm -f -- \"$dest_path\"" >> "$UNDO_SH"
  else
    dest_dir="$(dirname "$dest_path")"
    log "Ensuring destination dir exists: $dest_dir"
    if ! mkdir -p "$dest_dir"; then
      apply_err=$((apply_err+1))
      err "MKDIR_ERROR: $dest_dir (for $dest_path)"
      printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$dest_path\"" "\"$date_added\"" "\"$sha\"" "MKDIR_ERROR" >> "$MAP_CSV"
      continue
    fi

    log "APPLY: copying: cp -p -- \"$f\" \"$dest_path\""
    if cp -p -- "$f" "$dest_path"; then
      apply_ok=$((apply_ok+1))
      log "COPIED_OK: $f -> $dest_path"
      printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$dest_path\"" "\"$date_added\"" "\"$sha\"" "COPIED_OK" >> "$MAP_CSV"
      echo "rm -f -- \"$dest_path\"" >> "$UNDO_SH"
    else
      apply_err=$((apply_err+1))
      err "COPY_ERROR: $f -> $dest_path"
      printf '%s,%s,%s,%s,%s\n' "\"$f\"" "\"$dest_path\"" "\"$date_added\"" "\"$sha\"" "COPY_ERROR" >> "$MAP_CSV"
      echo "# FAILED: rm -f -- \"$dest_path\"" >> "$UNDO_SH"
    fi
  fi

  (( total_scanned % 100 == 0 )) && log "Progress: processed $total_scanned audio files (git-evaluated)"

done < <(python - <<'PY' "$sorted_list_file"
import sys
data = open(sys.argv[1], "rb").read().split(b"\0")
for r in data:
    if r:
        sys.stdout.buffer.write(r + b"\0")
PY
)

cleanup
rm -f "$sorted_list_file" 2>/dev/null || true

log "----"
log "Finished processing."

echo ""
echo "Summary:"
echo "  Git-evaluated audio files:     $total_scanned"
echo "  Skipped (already prefixed):    $skipped_prefixed"
echo "  Skipped (precheck exists):     $skipped_precheck_exists"
echo "  Skipped (already exists):      $skipped_already_exists"
echo "  Skipped (inside $DEST_ROOT/):  $skipped_in_dest_root"
echo "  No add-commit found:           $no_add_commit"
echo "  Planned copies:                $planned_copies"
if [[ "$MODE" == "apply" ]]; then
  echo "  Copied OK:                     $apply_ok"
  echo "  Copy errors:                   $apply_err"
fi
echo "  Non-audio files encountered:   $non_audio_seen"

echo ""
echo "Top 20 dates by file count (YYYYMMDD):"
if (( ${#date_counts[@]} > 0 )); then
  for d in "${!date_counts[@]}"; do
    echo "${date_counts[$d]} $d"
  done | sort -nr | head -20 | awk '{printf "  %s (%s files)\n",$2,$1}'
else
  echo "  (none)"
fi

echo ""
echo "First 30 examples:"
if (( ${#examples[@]} == 0 )); then
  echo "  (none)"
else
  for ex in "${examples[@]}"; do
    echo "  $ex"
  done
fi

echo ""
echo "Wrote:"
echo "  $MAP_CSV"
echo "  $UNDO_SH"

if [[ "$MODE" == "dry-run" ]]; then
  echo ""
  echo "Next:"
  echo "  Run with --apply to execute copies:"
  echo "    ./$0 --apply"
  echo "  Or reduce logs:"
  echo "    ./$0 --dry-run --quiet"
fi
