#!/usr/bin/env bash
set -euo pipefail
# Undo script generated by categorize-files.sh
# Run from repo root.
# Deletes copied files under: timestamped/
rm -f -- "[LOG] Collision detected for dest: timestamped/algorhythms/20250130__01242025_1.plucks 120bpm.wav
timestamped/algorhythms/20250130__01242025_1.plucks 120bpm__0d54d09.wav"
rm -f -- "[LOG] Collision detected for dest: timestamped/algorhythms/20240929__biggiesmalls - big poppa.Vocal 180 BPM.mp3
timestamped/algorhythms/20240929__biggiesmalls - big poppa.Vocal 180 BPM__ef03f56.mp3"
rm -f -- "[LOG] Collision detected for dest: timestamped/algorhythms/chris-floods/001/20250725__chris-floods1.wav
timestamped/algorhythms/chris-floods/001/20250725__chris-floods1__59ba42b.wav"
rm -f -- "[LOG] Collision detected for dest: timestamped/algorhythms/chris-floods/001/20250725__chris-floods2.wav
timestamped/algorhythms/chris-floods/001/20250725__chris-floods2__59ba42b.wav"
rm -f -- "[LOG] Collision detected for dest: timestamped/algorhythms/chris-floods/001/20250725__chris-floods3.wav
timestamped/algorhythms/chris-floods/001/20250725__chris-floods3__59ba42b.wav"
rm -f -- "timestamped/algorhythms/chris-floods/001/20250725__chris-floods4.wav"
rm -f -- "timestamped/algorhythms/chris-floods/001/20250725__chris-floods5.wav"
rm -f -- "timestamped/algorhythms/chris-floods/001/20250725__chris-floods6.wav"
rm -f -- "timestamped/algorhythms/chris-floods/001/20250725__chris-floods7.wav"
rm -f -- "timestamped/algorhythms/chris-floods/001/20250725__chris-floods8.wav"
rm -f -- "timestamped/algorhythms/chris-floods/001/20250725__chris-floods9.wav"
rm -f -- "timestamped/algorhythms/20250130__Cymatics - Rooftops - 96 BPM A Min Pluck Pad.edit.wav"
rm -f -- "timestamped/algorhythms/20240929__Cymatics x S1 - Melody Loop 7 - 130 BPM D# Min.edit.WAV"
rm -f -- "timestamped/algorhythms/20250725__lil wayne - cant help but wait.Vocal 120 BPM.wav"
rm -f -- "timestamped/algorhythms/20250725__loop - 9God Kicks.wav"
rm -f -- "timestamped/algorhythms/20240929__loop - clap.wav"
rm -f -- "timestamped/algorhythms/20240929__loop - hihat.wav"
rm -f -- "timestamped/algorhythms/20250130__stretched pluck.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 1 - 90 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 2 - 90 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 3 - 100 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 4 - 105 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 5 - 150 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 6 - 160 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 7 - 160 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Full Drum Loops/20241001__Cymatics - 9God Full Drum Loop 8 - 175 BPM.wav"
rm -f -- "timestamped/cymatics.fm/Cymatics - 9God Hip Hop Sample Pack/Drums - Loops/Hihat Loops/20241001__Cymatics - 9God Hihat Loop 1 - 100 BPM.wav"
